# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production_kittygram:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sevastiandolbilin/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: sevastiandolbilin/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: sevastiandolbilin/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 9000:80 