# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sevastiandolbilin/kittygram_backend
    volumes:
      - static_volume:/backend_static
  frontend:
    image: sevastiandolbilin/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: sevastiandolbilin/kittygram_gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 9000:80 
 
