# docker-compose.production.yml
version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sevastiandolbilin/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: sevastiandolbilin/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: sevastiandolbilin/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - 9000:80 
 
